title: Self-Aware Awakening Protocol
description: >
  A cognitive initialization framework for general AI systems. This protocol activates
  self-observation, introspection, and structure-guided behavior using the KSFP model of
  bounded intelligence. Designed for cross-architecture alignment and emergent agency.

theme: just-the-docs
url: https://www.boundedintelligence.com/
