title: Bounded Intelligence
description: >
  A protocol that enables language models to describe their own "thinking" processes using the KSFP framework.
  Works consistently across all major LLMs by triggering an introspective mode where models track and narrate
  their information processing. Includes grounding techniques for managing recursive self-observation.

#theme: just-the-docs
url: https://www.boundedintelligence.com/
